configuration:
  configuration_dir: "commons/config"
  template_dir:
  - "commons/templates"
  - "setupmobans/templates"
  - ".moban.d"
  configuration: pyexcel-ezodf.yml
targets:
  - README.rst: README.rst
  - setup.py: setup.py
  - ezodf/_version.py: version.py.jj2
  - "tests/requirements.txt": "test_requirements.txt"
  - requirements.txt: requirements.txt